---
- name: Main Playbook
  hosts: 127.0.0.1
  connection: local

  vars_files:
    - default.config.yml

  tasks:
  - include_tasks: tasks/ansible-setup.yml
  - name: Show a Welcome message
    debug:
      msg: 'Welcome to the playbook execution !'
  - name: Install iTerm
    homebrew_cask:
      name: iterm2
      state: present
      install_options: force
  - name: Install Visual Studio Code
    homebrew_cask:
      name: visual-studio-code
      state: present
      install_options: force
  - name: Install AWS Cli
    homebrew:
      name: awscli
      state: present
  - name: Install Telegram
    homebrew_cask:
      name: telegram
      state: present
      install_options: force
  - name: Install Whatsapp
    homebrew_cask:
      name: whatsapp
      state: present
      install_options: force
  - name: Install Slack
    homebrew_cask:
      name: slack
      state: present
      install_options: force
  - name: Install Firefox
    homebrew_cask:
      name: firefox
      state: present
      install_options: force
  - name: Install Sublime Text
    homebrew_cask:
      name: sublime-text
      state: present
      install_options: force
  - name: Install Docker
    homebrew:
      name: docker
      state: present